config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root to: "offers#index"
  resources :offers do
    post "/:id", to: "bookings#create"
  end
  get "/offers/:offer_id/new_booking", to: "bookings#new", as: "new_booking"
  patch "bookings/:booking_id/accept", to:"bookings#accept", as: "accept_booking"
  patch "bookings/:booking_id/reject", to:"bookings#reject", as: "reject_booking"

  get "/listings", to: "listings#list", as: "listings"
  get "/subscriptions/", to: "subscriptions#list", as: "subscriptions"
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user

  validates :street, :city, :state, :country, :zip, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :offer

  validates :duration, presence: true

  
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo

  validates :plant_name, :price, presence: true

  include PgSearch::Model

  pg_search_scope :global_search,
  against: [ :plant_name, :plant_description ],
  associated_against: {
    user: [:username]
  },
  using: {
    tsearch: { prefix: true }
  }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :offers
  has_many :bookings
  has_one_attached :photo

  # validates :username, presence: true, uniqueness: true
  # validates :street, :city, :state, :country, :zip, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    @offer = Offer.find(params[:offer_id])
    @booking = Booking.new
  end

  def create
    @offer = Offer.find(params[:offer_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.offer = @offer
    if @booking.save
      redirect_to subscriptions_path(@offer)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def accept
    @booking = Booking.find(params[:booking_id])
    @booking.update(status: "accepted")
    @offer = @booking.offer
    @offer.update(status: false)
    redirect_to listings_path(active_tab: "accepted-requests")
  end

  def reject
    @booking = Booking.find(params[:booking_id])
    @booking.update(status: "rejected")
    redirect_to listings_path(active_tab: "rejected-requests")
  end

  private

  def booking_params
    params.require(:booking).permit(:comment, :duration)
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def list
    @available_offers = current_user.offers.where(status: true)
    @rented_offers = current_user.offers.where(status: false)

    @pending_requests = Booking.joins(offer: :user).where(status: "pending", offers: { user_id: current_user.id })
    @accepted_requests = Booking.joins(offer: :user).where(status: "accepted", offers: { user_id: current_user.id })
    @rejected_requests = Booking.joins(offer: :user).where(status: "rejected", offers: { user_id: current_user.id })
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  def index
    if params[:query].present?
      @offers = Offer.global_search(params[:query]).where(status: true)
    else
      @offers = Offer.where(status: true)
    end
  end

  def show
    @booking = Booking.new
    @offer = Offer.find(params[:id])
    if user_signed_in?
      @already_booked = Booking.where(user_id: current_user.id, offer_id: @offer, status: "accepted")
    end
  end

  def new
    @offer = Offer.new
  end

  def create
    @offer = Offer.new(offer_params)
    @offer.user = current_user
    @offer.save
    # No need for app/views/offers/create.html.erb
    redirect_to offer_path(@offer)
  end

  def edit
    @offer = Offer.find(params[:id])
  end

  def update
    @offer = Offer.find(params[:id])
    @offer.update(offer_params)
    redirect_to offer_path
  end

  def destroy
    @offer = Offer.find(params[:id])
    @offer.destroy
    redirect_to listings_path, status: :see_other
  end

  private

  def offer_params
    params.require(:offer).permit(:plant_name, :plant_description, :price, :photo)
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def list
    @active_subscriptions = Booking.joins(:offer).where(user_id: current_user.id, offers: { status: false })
    @past_subscriptions = Booking.joins(:offer).where(user_id: current_user.id, status: "accepted", offers: { status: true })

    @pending_subscriptions = Booking.where(user_id: current_user.id, status: "pending")
    @accepted_subscriptions = Booking.where(user_id: current_user.id, status: "accepted")
    @rejected_subscriptions = Booking.where(user_id: current_user.id, status: "rejected")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<%= simple_form_for([@offer, @booking], url: new_booking_path(@offer)) do |f| %>
  <%= f.input :comment %>
  <%= f.input :duration, as: :integer, label: "Duration (in months)", input_html: { min: 1, step: 1, placeholder: "Enter duration in months" } %>
  <%= f.button :submit, 'Rent this plant', class: 'btn btn-success' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Plantlord</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('22328seedling_98726.png') %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body id="body">
    <div class="page-container">
      <%= render "shared/flashes" %>
      <div class="navbar-container"><%= render "shared/navbar" %></div>
      <div class="content-container container mt-5">
        <div class="mt-3">
          <%= yield %>
        </div>
      </div>
      <div class="footer-container"><%= render "shared/footer" %></div>
    </div>
  </body>
</html>

app/views/listings/list.html.erb
<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link <%= "#{params[:active_tab]=='accepted-requests' || params[:active_tab]=='rejected-requests' ? '' : 'active' }" %>" id="listings-tab" data-bs-toggle="tab" data-bs-target="#listings-tab-pane" type="button" role="tab" aria-controls="listings-tab-pane" aria-selected="true">My listings</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link <%= "#{params[:active_tab]=='accepted-requests' || params[:active_tab]=='rejected-requests' ? 'active' : '' }" %>" id="user-requests-tab" data-bs-toggle="tab" data-bs-target="#user-requests-tab-pane" type="button" role="tab" aria-controls="user-requests-tab-pane" aria-selected="false">Incoming requests</button>
  </li>
</ul>

<div class="tab-content" id="myTabContent">
  <div class="<%= "#{params[:active_tab]=='accepted-requests' || params[:active_tab]=='rejected-requests' ? '' : 'active show' }" %> tab-pane fade show mt-3" id="listings-tab-pane" role="tabpanel" aria-labelledby="listings-tab" tabindex="0">
    <p>Available listings</p>
    <div class="container">
      <div class="row">
        <% @available_offers.each do |offer| %>
          <div class="col-md-3 mb-4">
            <%= render "shared/plant_card_listings", offer: offer %>
          </div>
        <% end %>
      </div>
    </div>
    <hr>
    <p>Rented listings</p>
    <div class="container">
      <div class="row">
        <% @rented_offers.each do |offer| %>
          <div class="col-md-3 mb-4">
            <%= link_to offer_path(offer) do %>
              <%= render "shared/plant_card", offer: offer %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="<%= "#{params[:active_tab]=='accepted-requests' || params[:active_tab]=='rejected-requests' ? 'active show' : '' }" %> tab-pane fade mt-3" id="user-requests-tab-pane" role="tabpanel" aria-labelledby="user-requests-tab" tabindex="0">
    <button class="btn btn-flat-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#pending-requests" aria-expanded="true" aria-controls="accepted-requests">
      Pending user requests
    </button>
    <div class="collapse show" id="pending-requests">
      <div class="card card-body">
        <div class="container">
          <div class="row">
            <% if @pending_requests == [] %>
              <div class="mb-4">
                <p>No pending requests.</p>
              </div>
            <% else %>
              <% @pending_requests.reverse_each do |request| %>
                <div class="mb-4">
                  <%= render "shared/request_card", offer: request.offer, request: request %>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <hr>
    <button class="btn btn-flat-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#accepted-requests" aria-expanded="<%= "#{params[:active_tab]=='incoming-requests' ? 'true' : 'false' }" %>" aria-controls="accepted-requests">
      Accepted user requests
    </button>
    <div class="collapse <%= "#{params[:active_tab]=='accepted-requests' ? 'show' : '' }" %>" id="accepted-requests">
      <div class="card card-body">
        <div class="container">
          <div class="row">
            <% @accepted_requests.reverse_each do |request| %>
              <div class="mb-4">
                <%= render "shared/request_card", offer: request.offer, request: request %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <hr>
    <button class="btn btn-flat-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#rejected-requests" aria-expanded="false" aria-controls="rejected-requests">
      Rejected user requests
    </button>
    <div class="collapse <%= "#{params[:active_tab]=='rejected-requests' ? 'show' : '' }" %>" id="rejected-requests">
      <div class="card card-body">
        <div class="container">
          <div class="row">
            <% @rejected_requests.reverse_each do |request| %>
              <div class="mb-4">
                <%= render "shared/request_card", offer: request.offer, request: request %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/offers/edit.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <p class="h4 mb-3 text-center">Edit <%= @offer.plant_name %></p>
      <%= simple_form_for(@offer, html: { class: "needs-validation" }) do |f| %>
        <div class="mb-3">
          <%= f.input :plant_name, input_html: { class: "form-control", placeholder: "Enter plant name" }, label_html: { class: "form-label" } %>
        </div>
        <div class="mb-3">
          <%= f.input :plant_description, input_html: { class: "form-control", placeholder: "Enter plant description" }, label_html: { class: "form-label" } %>
        </div>
        <div class="mb-3">
          <%= f.input :price, input_html: { class: "form-control", placeholder: "Enter price" }, label_html: { class: "form-label" } %>
        </div>
        <div class="mb-3">
          <%= f.input :photo, as: :file, input_html: { class: "form-control" }, label_html: { class: "form-label" } %>
        </div>
        <div class="d-grid">
          <%= f.submit "Update Offer", class: "btn btn-flat btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/offers/index.html.erb
<h1>Plant Offers</h1>
<div class="container">
  <div class="row">
    <% @offers.each do |offer| %>
      <div class="col-md-3 mb-4">
        <%= link_to offer_path(offer) do %>
        <%= render "shared/plant_card", offer: offer %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/offers/new.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <p class="h4 mb-3 text-center">Add a New Offer</p>
      <%= simple_form_for(@offer, html: { class: "needs-validation" }) do |f| %>
        <div class="mb-3">
          <%= f.input :plant_name, input_html: { class: "form-control", placeholder: "Enter plant name" }, label_html: { class: "form-label" } %>
        </div>
        <div class="mb-3">
          <%= f.input :plant_description, input_html: { class: "form-control", placeholder: "Enter plant description" }, label_html: { class: "form-label" } %>
        </div>
        <div class="mb-3">
          <%= f.input :price, input_html: { class: "form-control", placeholder: "Enter price" }, label_html: { class: "form-label" } %>
        </div>
        <div class="mb-3">
          <%= f.input :photo, as: :file, input_html: { class: "form-control" }, label_html: { class: "form-label" } %>
        </div>
        <div class="d-grid">
          <%= f.submit "Create Offer", class: "btn btn-flat btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/offers/show.html.erb
<div class="plant-card-product card-product position-relative">
  <%= cl_image_tag @offer.photo.key, height: 300, width: 300 %>
  <div class="plant-card-product-infos card-product-infos">
    <h2><%= @offer.plant_name %></h2>
    <p><%= @offer.plant_description %></p>
    <p><%= @offer.price %> € / month</p>

    <div class="mt-3">
      <% unless user_signed_in? %>
        <%= link_to "Log in to rent this plant", new_user_session_path, class: "btn btn-flat" %>
      <% end %>
      <% if user_signed_in? && current_user.id != @offer.user_id && !@already_booked.empty? %>
        <p>You are currently renting this plant!</p>
      <% end %>

      <% if user_signed_in? && current_user.id != @offer.user_id && @already_booked.empty? %>
        <button type="button" class="btn btn-flat" data-bs-toggle="modal" data-bs-target="#rentPlantModal">
          Rent this plant
        </button>

        <div class="modal fade" id="rentPlantModal" tabindex="-1" aria-labelledby="rentPlantModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="rentPlantModalLabel">Rent this plant</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <%= simple_form_for([@offer, @booking], url: new_booking_path(@offer)) do |f| %>
                  <%= f.input :comment %>
                  <%= f.input :duration, as: :integer, label: "Duration", input_html: { min: 1, step: 1, placeholder: "Enter duration in months" } %>
                  <%= f.button :submit, 'Rent this plant', class: 'btn btn-flat' %>
                <% end %>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      <% if user_signed_in? && current_user.id == @offer.user_id %>
        <%= link_to "Edit", edit_offer_path(@offer), class: "btn btn-flat-secondary" %>
        <%= link_to "Delete", offer_path(@offer), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-flat-secondary-danger" %>
      <% end %>

    </div>
  </div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-container">
    <div class="footer-icons">
      <%= image_tag "plant_icon_1.png", alt: "plant" %>
      <%= image_tag "plant_icon_2.png", alt: "plant" %>
      <%= image_tag "plant_icon_3.png", alt: "plant" %>
      <%= image_tag "plant_icon_1.png", alt: "plant" %>
      <%= image_tag "plant_icon_2.png", alt: "plant" %>
      <%= image_tag "plant_icon_3.png", alt: "plant" %>
      <%= image_tag "plant_icon_1.png", alt: "plant" %>
      <%= image_tag "plant_icon_2.png", alt: "plant" %>
      <%= image_tag "plant_icon_3.png", alt: "plant" %>
      <%= image_tag "plant_icon_1.png", alt: "plant" %>
      <%= image_tag "plant_icon_2.png", alt: "plant" %>
      <%= image_tag "plant_icon_3.png", alt: "plant" %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar fixed-top navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      🌱 <strong>Plant</strong>lord
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "My subscriptions", subscriptions_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My listings", listings_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Create listing", new_offer_path, class: "nav-link" %>
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to "Create listing", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>

      <div class="d-flex search-and-avatar">

        <%= form_with url: offers_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query, params[:query], class: "form-control me-2", placeholder: "Type a keyword" %>
        <%= submit_tag "Search", name: "", class: "btn btn-flat-secondary" %>
        <% end %>

        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <%= cl_image_tag current_user.photo.key, class: "avatar-bordered dropdown-toggle", id: "navbarDropdown", data:{bs_toggle: "dropdown"}, aria_haspopup: "true", aria_expanded: "false" %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: { turbo_method: :delete } %>
              </div>
            </li>
            <% else %>
            <div class="d-flex justify-content-evenly">
              <%= link_to "Register", new_user_registration_path, class: "btn btn-secondary" %>
              <%= link_to "Log in", new_user_session_path, class: "ms-1 btn btn-secondary" %>

            </div>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_plant_card.html.erb
<div class="card plant-card">

  <div style="background-image: url('<%= cl_image_path(offer.photo.key, height: 300, width: 300) %>');
  background-size: cover; height: 300px" >
  </div>
    <div class="card-body plant-card-body d-flex flex-column justify-content-between">
      <h5 class="card-title plant-card-title"><strong><%= offer.plant_name %></strong></h5>
      <p class="card-text plant-card-text"><%= offer.plant_description %></p>
      <h6 class="card-price plant-card-price">€<strong><%= offer.price %> / month</strong></h6>
    </div>
    <div class="card-footer plant-card-footer">
      <div class="d-flex justify-content-between">
        <%= cl_image_tag offer.user.photo.key, class: "avatar-bordered", alt: "avatar-bordered", crop: :thumb, gravity: :face %>
        <%# <img src="https://icons.veryicon.com/png/o/miscellaneous/common-area-icons/default-avatar-1.png" class="avatar img-fluid" alt="User avatar" /> %>
        <h6 class="mt-2"><%= offer.user.username %></h6>
      </div>
    </div>
</div>

app/views/shared/_plant_card_listings.html.erb
<div class="card plant-card">

  <%= link_to "", offer_path(offer), class: "card-link" %>
  <div style="background-image: url('<%= cl_image_path(offer.photo.key, height: 300, width: 300) %>');
  background-size: cover; height: 300px" >
    <div class='card-buttons'>
      <%= link_to "Edit", edit_offer_path(offer), class: "btn btn-flat-secondary-small" %>
      <%= link_to "Delete", offer_path(offer), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn-delete-small" %>
    </div>
  </div>
    <div class="card-body plant-card-body d-flex flex-column justify-content-between">
      <h5 class="card-title plant-card-title"><strong><%= offer.plant_name %></strong></h5>
      <p class="card-text plant-card-text"><%= offer.plant_description %></p>
      <h6 class="card-price plant-card-price">€<strong><%= offer.price %></strong></h6>
    </div>
    <div class="card-footer plant-card-footer">
      <div class="d-flex justify-content-between">
        <%= cl_image_tag offer.user.photo.key, class: "avatar-bordered", alt: "avatar-bordered", crop: :thumb, gravity: :face %>
        <%# <img src="https://icons.veryicon.com/png/o/miscellaneous/common-area-icons/default-avatar-1.png" class="avatar img-fluid" alt="User avatar" /> %>
        <h6 class="mt-2"><%= offer.user.username %></h6>
      </div>
    </div>
</div>

app/views/shared/_request_card.html.erb
<div class="request-card">
  <%= link_to offer_path(request.offer) do %>
    <div><%= cl_image_tag offer.photo.key, height: 300, width: 300 %></div>
  <% end %>
  <div class="request-card-infos col-2">
    <h2><%= offer.plant_name %></h2>
    <p>€<%= offer.price %></p>
  </div>
  <div>
    <%= cl_image_tag request.user.photo.key, class: "avatar" %>
  </div>
  <div class="request-card-infos">
    <p>Requested by:</p>
    <h2><%= request.user.username %></h2>
  </div>
  <div class="request-card-infos">
    <p>Requested duration:</p>
    <p><%= request.duration %></p>
    <p>Comment:</p>
    <p><%= request.comment %></p>
  </div>
  <% if request.status == "pending" %>
    <div class="align-right">
      <div class="d-grid gap-1">
        <%= link_to "accept", accept_booking_path(booking_id: request.id), data: { turbo_method: :patch }, class: "btn btn-success mb-2" %>
        <%= link_to "reject", reject_booking_path(booking_id: request.id), data: { turbo_method: :patch }, class: "btn btn-danger" %>
      </div>
    </div>
  <% end %>

</div>

app/views/subscriptions/list.html.erb
<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="subscriptions-tab" data-bs-toggle="tab" data-bs-target="#subscriptions-tab-pane" type="button" role="tab" aria-controls="subscriptions-tab-pane" aria-selected="true">My subscriptions</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="my-requests-tab" data-bs-toggle="tab" data-bs-target="#my-requests-tab-pane" type="button" role="tab" aria-controls="my-requests-tab-pane" aria-selected="false">My requests</button>
  </li>
</ul>

<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active mt-3" id="subscriptions-tab-pane" role="tabpanel" aria-labelledby="subscriptions-tab" tabindex="0">
    <p>Active subscriptions</p>
    <div class="container">
      <div class="row">
        <% @active_subscriptions.each do |subscription| %>
          <div class="col-md-3 mb-4">
            <%= link_to offer_path(subscription.offer_id) do %>
              <%= render "shared/plant_card", offer: Offer.where(id: subscription.offer_id)[0] %>
            <% end %>
          </div>
        <% end %>

      </div>
    </div>
    <hr>
    <p>Past subscriptions</p>
    <div class="container">
      <div class="row">
        <% @past_subscriptions.each do |subscription| %>
          <div class="col-md-3 mb-4">
            <%= link_to offer_path(subscription.offer_id) do %>
              <%= render "shared/plant_card", offer: Offer.where(id: subscription.offer_id)[0] %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="tab-pane fade  mt-3" id="my-requests-tab-pane" role="tabpanel" aria-labelledby="my-requests-tab" tabindex="0">
    <p>Pending requests</p>
    <div class="container">
      <div class="row">
        <% @pending_subscriptions.reverse_each do |subscription| %>
          <div class="col-md-3 mb-4">
            <%= link_to offer_path(subscription.offer_id) do %>
              <%= render "shared/plant_card", offer: Offer.where(id: subscription.offer_id)[0] %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <hr>
    <button class="btn btn-flat-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseAccepted" aria-expanded="false" aria-controls="collapseExample">
      Accepted requests
    </button>
    <div class="collapse" id="collapseAccepted">
      <div class="card card-body">
        <div class="container">
          <div class="row">
            <% @accepted_subscriptions.reverse_each do |subscription| %>
              <div class="col-md-3 mb-4">
                <%= link_to offer_path(subscription.offer_id) do %>
                  <%= render "shared/plant_card", offer: Offer.where(id: subscription.offer_id)[0] %>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <hr>
    <button class="btn btn-flat-secondary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseRejected" aria-expanded="false" aria-controls="collapseExample">
      Rejected requests
    </button>
    <div class="collapse" id="collapseRejected">
      <div class="card card-body">
        <div class="container">
          <div class="row">
            <% @rejected_subscriptions.reverse_each do |subscription| %>
              <div class="col-md-3 mb-4">
                <%= link_to offer_path(subscription.offer_id) do %>
                  <%= render "shared/plant_card", offer: Offer.where(id: subscription.offer_id)[0] %>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>